export const projects = [
  {
    id: 1,
    title: "AI Agent Orchestrator",
    description: "Multi-agent system using n8n workflows for automated research pipelines. Combines RAG with OpenAI Agents for intelligent document processing.",
    tags: ["AI", "n8n", "RAG", "OpenAI"],
    category: "AI",
    link: "#",
    github: "#",
    image: null,
  },
  {
    id: 2,
    title: "Social Behavior Analyzer",
    description: "RAG-powered system that analyzes social media patterns to predict behavioral trends. Bridges sociology research with machine learning.",
    tags: ["AI", "Python", "RAG", "NLP"],
    category: "AI",
    link: "#",
    github: "#",
    image: null,
  },
  {
    id: 3,
    title: "Portfolio Platform",
    description: "Full-stack portfolio with Next.js 15, R3F 3D scenes, and glass-morphism design. Real-time performance monitoring and SEO optimization.",
    tags: ["Next.js", "React", "Three.js", "Tailwind"],
    category: "Fullstack",
    link: "#",
    github: "#",
    image: null,
  },
  {
    id: 4,
    title: "E-Commerce Dashboard",
    description: "Real-time analytics dashboard with WebSocket updates, interactive charts, and role-based access control for multi-tenant SaaS.",
    tags: ["React", "Node.js", "PostgreSQL", "WebSocket"],
    category: "Fullstack",
    link: "#",
    github: "#",
    image: null,
  },
  {
    id: 5,
    title: "use-debounce-query",
    description: "React hook for debounced API queries with TypeScript support. 500+ weekly downloads, zero dependencies, fully tree-shakeable.",
    tags: ["NPM", "React", "TypeScript"],
    category: "NPM",
    link: "#",
    github: "#",
    image: null,
  },
  {
    id: 6,
    title: "n8n-node-contrib",
    description: "Custom n8n node for AI-powered text classification. Enables no-code users to integrate ML models into their workflows.",
    tags: ["NPM", "n8n", "AI"],
    category: "NPM",
    link: "#",
    github: "#",
    image: null,
  },
  {
    id: 7,
    title: "Agent Maturity Model",
    description: "Interactive framework for evaluating AI agent capabilities from Bronze to Gold tier. Used by 200+ developers for agent assessment.",
    tags: ["AI", "Framework", "Research"],
    category: "AI",
    link: "#",
    github: "#",
    image: null,
  },
  {
    id: 8,
    title: "Real-time Chat Platform",
    description: "End-to-end encrypted messaging with WebRTC video calls. Built with Next.js, Socket.io, and Redis for session management.",
    tags: ["Next.js", "Socket.io", "Redis", "WebRTC"],
    category: "Fullstack",
    link: "#",
    github: "#",
    image: null,
  },
];

export const workCategories = ['All', 'AI & Agents', 'Fullstack', 'NPM'] as const;

export type WorkProject = {
  id: number;
  category: string;
  icon: string;
  title: string;
  badge: string;
  what: string;
  why: string;
  result: string;
  screenshot: string;
  architectureSvg?: string;
  links: { demo?: string; github?: string; architecture?: string };
  demoLabel?: string;
  tags: string[];
  accent: 'magenta' | 'teal' | 'purple';
};

export const workProjects: WorkProject[] = [
  {
    id: 1,
    category: 'AI & Agents',
    icon: 'Bot',
    title: 'CRM DIGITAL FTE FACTORY',
    badge: 'GIAIC — HACKATHON 5 (ADVANCED)',
    what: 'AI employee handling every channel autonomously — 24/7, zero human input.',
    why: 'Businesses waste 30+ hours weekly on Gmail, WhatsApp and CRM manually.',
    result: 'Zero hours needed. Live in production.',
    screenshot: '/projects/crm/screenshot.png',
    links: { demo: 'https://youtu.be/WlHItrNs8Z8', github: '#', architecture: '#' },
    tags: ['OpenAI Agents SDK', 'Kafka', 'Docker', 'MCP'],
    accent: 'magenta',
  },
  {
    id: 2,
    category: 'AI & Agents',
    icon: 'Smartphone',
    title: 'PERSONAL AI EMPLOYEE (DIGITAL FTE)',
    badge: 'GIAIC — HACKATHON 0 (ADVANCED)',
    what: 'Standard automation tools stay entirely passive, waiting for manual prompt inputs while daily business tasks exhaust 40+ hours.',
    why: 'Autonomous agent running 24/7 via file watchers, Claude Code reasoning engine, MCP servers, and an Obsidian GUI dashboard.',
    result: 'Zero prompt inputs needed. Self-iterating execution loops handle business affairs completely on autopilot.',
    screenshot: '/projects/ai-employee/screenshot.svg',
    links: { demo: '#', github: 'https://github.com/EmanIqbal620/Full-Time-AI-Employee.git' },
    tags: ['Claude Code', 'MCP Servers', 'Python Watchers', 'Obsidian GUI'],
    accent: 'magenta',
  },
  {
    id: 8,
    category: 'Fullstack',
    icon: 'BookOpen',
    title: 'HUMANOID ROBOTICS BOOK + RAG AI TUTOR',
    badge: 'GIAIC — HACKATHON 1',
    what: 'Free textbook with 6 modules and a live RAG AI Tutor built in.',
    why: 'Robotics education is expensive, scattered and paywalled.',
    result: '6 modules • 24+ weeks • Live RAG AI Tutor — deployed free. Anyone can access and learn right now.',
    screenshot: '/projects/humanoid-robotics/screenshot.png',
    architectureSvg: '/projects/humanoid-robotics/architecture.svg',
    links: { demo: 'https://ai-native-book-ruddy.vercel.app', github: 'https://github.com/EmanIqbal620/ai-native-book.git', architecture: '#' },
    tags: ['Docusaurus', 'RAG', 'Qdrant', 'FastAPI', 'Neon PostgreSQL'],
    accent: 'teal',
  },
  {
    id: 5,
    category: 'Fullstack',
    icon: 'CheckSquare',
    title: 'TODOFLOW AI TASK MANAGER',
    badge: 'GIAIC — HACKATHON 3',
    what: 'Full app with auth, analytics, AI chatbot built in 3 phases.',
    why: 'Todo apps store tasks but never help you think or prioritize.',
    result: 'Live on Vercel. Works right now.',
    screenshot: '/projects/todoflow/screenshot.png',
    architectureSvg: '/projects/todoflow/architecture.svg',
    links: { demo: 'https://tobo-app-chatbot.vercel.app', github: 'https://github.com/EmanIqbal620/tobo-app-chatbot.git' },
    tags: ['Next.js', 'FastAPI', 'Better Auth', 'JWT', 'Neon PostgreSQL'],
    accent: 'magenta',
  },
  {
    id: 4,
    category: 'AI & Agents',
    icon: 'MessageSquare',
    title: 'AI CHAT — CHAINLIT + GEMINI',
    badge: 'DEPLOYED ON HUGGING FACE ✦',
    what: 'Built a full AI chat interface with Gemini API backend and real-time streaming deployed to production.',
    why: 'Most developers use ChatGPT without understanding how to build one themselves.',
    result: 'Live on Hugging Face with real-time streaming — deployed and working.',
    screenshot: '/projects/chainlit/screenshot.png',
    links: { demo: 'https://emaniqbal-chainlit1.hf.space', github: 'https://github.com/EmanIqbal620/chainlit.git' },
    tags: ['Chainlit', 'Python', 'Gemini API'],
    accent: 'magenta',
  },
  {
    id: 6,
    category: 'Fullstack',
    icon: 'ShoppingCart',
    title: 'TULIP FLOWER SHOP',
    badge: 'GIAIC — HACKATHON ✦',
    what: 'Complete online flower store — 12+ products, pricing with discounts, cart, reviews and contact. Built and deployed.',
    why: 'Most student e-commerce projects are fake. This one has real auth, real CMS, real flow.',
    result: 'Built and deployed on Vercel.',
    screenshot: '/projects/tulip/screenshot.png',
    links: { demo: 'https://tulip-e-commerce-web-42fy.vercel.app/', github: 'https://github.com/EmanIqbal620/tulip-E-commerce-web.git' },
    tags: ['Next.js', 'Tailwind CSS', 'Vercel', 'Sanity CMS'],
    accent: 'teal',
  },
  {
    id: 7,
    category: 'Fullstack',
    icon: 'FileText',
    title: 'BLOG — SOCIOLOGY & TECH',
    badge: 'DEPLOYED ON VERCEL ✦',
    what: 'Built a modern blogging platform with responsive layouts and clean content-focused UI.',
    why: 'Designed scalable frontend architecture optimized for readability and seamless navigation.',
    result: 'Focused on performance, responsive design, and improved user experience.',
    screenshot: '/projects/blog/screenshot.png',
    links: { demo: 'https://blog-web-kappa-lime.vercel.app/', github: 'https://github.com/EmanIqbal620/blog-web.git' },
    tags: ['Next.js', 'Sanity CMS', 'Tailwind', 'Vercel'],
    accent: 'teal',
  },
  {
    id: 9,
    category: 'NPM',
    icon: 'Package',
    title: '12 TYPESCRIPT CLI PACKAGES',
    badge: '📦 OPEN SOURCE — NPM',
    what: 'Published a collection of 12 open-source TypeScript CLI tools and interactive terminal utilities to NPM.',
    why: 'Developers rebuild the same terminal utilities in every project.',
    result: '12 packages live on NPM right now. This suite demonstrates a solid foundation in modular package design, strict type safety, and automated node-based command-line architectures.',
    screenshot: '/projects/npm-packages/screenshot.png',
    links: { demo: 'https://www.npmjs.com/~eman_iqbal', github: '#' },
    demoLabel: 'VIEW ON NPM',
    tags: ['TypeScript', 'NPM', 'CLI', 'inquirer', 'chalk'],
    accent: 'purple',
  },
  {
    id: 11,
    category: 'Fullstack',
    icon: 'ShoppingCart',
    title: 'FURNITURE E-COMMERCE',
    badge: 'DEPLOYED ON VERCEL ✦',
    what: 'Full production furniture store with Sanity CMS product management, cart functionality and complete shopping flow.',
    why: 'Most e-commerce tutorials stop before deployment. This one ships.',
    result: 'Built and deployed on Vercel with real products and full shopping flow.',
    screenshot: '/projects/furniture/screenshot.png',
    links: { demo: 'https://tulip-e-commerce-web-42fy.vercel.app/', github: 'https://github.com/EmanIqbal620/tulip-E-commerce-web.git' },
    tags: ['Next.js', 'Sanity CMS', 'Tailwind CSS', 'Clerk'],
    accent: 'teal',
  },
];

export const navItems = [
  { label: "Home", href: "#home" },
  { label: "What I Build", href: "#what-i-build" },
  { label: "Work", href: "#work" },
  { label: "About", href: "#about" },
  { label: "Tech Stack", href: "#tech-stack" },
  { label: "Contact", href: "#contact" },
];
